//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calisanlar()
        {
            this.Calisanlar1 = new HashSet<Calisanlar>();
            this.EmanetEsyalar = new HashSet<EmanetEsyalar>();
            this.Siparisler = new HashSet<Siparisler>();
        }
    
        public int CalisanID { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public string CalisanAdi { get; set; }
        public string CalisanSoyAdi { get; set; }
        public string Unvan { get; set; }
        public Nullable<int> RaporVerecegiKisi { get; set; }
        public bool Durum { get; set; }
    
        public virtual CalisanDetay CalisanDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calisanlar> Calisanlar1 { get; set; }
        public virtual Calisanlar Calisanlar2 { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmanetEsyalar> EmanetEsyalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
    }
}
