//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmanetEsyalar
    {
        public int EmanetEsyaID { get; set; }
        public Nullable<int> CalisanID { get; set; }
        public string EsyaAdi { get; set; }
        public System.DateTime VerilmeTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public bool Durum { get; set; }
    
        public virtual Calisanlar Calisanlar { get; set; }
    }
}
