//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyonlar
    {
        public int ReverzasyonID { get; set; }
        public int MusteriID { get; set; }
        public int MasaID { get; set; }
        public Nullable<System.DateTime> RezervasyonTarihi { get; set; }
    
        public virtual Masa Masa { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
