//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.SiparisUrunDetay = new HashSet<SiparisUrunDetay>();
        }
    
        public int UrunID { get; set; }
        public int RestaurantMenuID { get; set; }
        public string UrunAdi { get; set; }
        public bool Durum { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual RestaurantMenu RestaurantMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisUrunDetay> SiparisUrunDetay { get; set; }
    }
}
